### ISSUE TITLE
插件依赖文件应当放在哪里

### ISSUE THREAD

**Issue by Hellobaka** [iTXTech/mirai-native#101]
**插件信息**
C#编写 依赖于CefSharp的原生酷Q Dll插件

**请求描述**
CefSharp有大量的依赖库
![image](https://user-images.githubusercontent.com/50934714/95934091-9952dc80-0e02-11eb-8511-ea5fdb598fa0.png)

这些依赖无法通过Fody打包进一个dll，所以想知道这些文件应当放在哪个目录内

已经尝试过的位置：
`mirai\libraries` (正常加载，进入启动事件内，因依赖缺失爆炸)
`mirai` (正常加载，进入启动事件内，因依赖缺失爆炸)
`mirai\data\MiraiNative\libraries`  不能正常加载 错误信息：

```
2020-10-14 09:53:19 E/MiraiNative: java.lang.UnsatisfiedLinkError: E:\QQBot\mirai-console-onkey\data\MiraiNative\libraries\CefSharp.BrowserSubprocess.Core.dll: Can't find dependent libraries
java.lang.UnsatisfiedLinkError: E:\QQBot\mirai-console-onkey\data\MiraiNative\libraries\CefSharp.BrowserSubprocess.Core.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1088)
        at org.itxtech.mirainative.manager.LibraryManager.load(LibraryManager.kt:33)
        at org.itxtech.mirainative.MiraiNative.checkNativeLibs(MiraiNative.kt:82)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:162)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:191)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:194)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)
```

**运行环境**
 - 操作系统：Windows 10 2004
 - `mirai core` 版本：mirai-core-qqandroid-1.2.3
 - `mirai console` 版本：mirai-console-pure-1.0-M4
 - `mirai native` 版本：mirai-native-1.9.3.jar
 - `Java` 运行时版本：11.0.8 x86

**Comment by Hellobaka** [comment]
插件补充：https://cloud.189.cn/t/iMJbAfm6vIRj

**Comment by PeratX** [comment]
`mirai\data\MiraiNative\libraries`是正确的文件夹，`提示依赖缺失`请补齐依赖的 `dll`文件

**Comment by PeratX** [comment]
如有跟进，请继续评论，issue会被重开。
