### ISSUE TITLE
插件运行错误

### ISSUE THREAD

**Issue by wqy0916** [iTXTech/mirai-native#109]
**描述这个Bug**
搜图的时候会报“图片下载失败，错误信息:在 WebClient 请求期间发生异常。”的错误信息，我在其他软件试过了不是插件的问题

**复现步骤**
一直这样
**期望的行为**
希望能修复一下

**截图和日志**
![image](https://user-images.githubusercontent.com/38550132/99968498-1b82d900-2d91-11eb-8bcb-ecbc534207d2.png)
2020-11-23 21:29:07 V/Bot 3026455775: Group(723263140) <- 正在查询关键字为康娜的插画信息，请等待……
2020-11-23 21:29:07 V/Bot 3026455775: Group(723263140) <- 拉取图片中~至少需要15s……\n你今日剩余调用次数为0次(￣▽￣)
2020-11-23 21:29:07 I/MiraiNative: [水银涩图机 搜索详情] 详情获取成功，正在拉取图片
2020-11-23 21:29:07 I/MiraiNative: [水银涩图机 搜索详情] 图片下载失败，错误信息:在 WebClient 请求期间发生异常。
2020-11-23 21:29:07 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.sendMessage(GroupImpl.kt:293)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:155)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**运行环境**
 - 操作系统：windows 10 1903
 - `mirai core` 版本：1.3.3
 - `mirai console` 版本：1.0.0
 - `mirai native` 版本：1.9.3
 - `Java` 运行时版本：11.0.8 x86

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by shabby2333** [comment]
这种大概率是你自己native插件的http请求出问题了 并且你没处理QwQ
