### ISSUE TITLE
加载native出错

### ISSUE THREAD

**Issue by yimo0908** [iTXTech/mirai-native#110]
**描述这个Bug**
mcl 1.0.2 加载native1.9.3出错

**复现步骤**
powershell管理员模式运行命令`java -jar mcl.jar`

**期望的行为**
成功加载

**截图和日志**
![image](https://user-images.githubusercontent.com/53830825/99968545-388ccb80-2dd4-11eb-8b5f-dbd705117246.png)
```
PS E:\test\mcl> java -jar mcl.jar
 21:30:11 [INFO] Mirai Console Loader version 1.0.2-a374eff
 21:30:11 [INFO] https://github.com/iTXTech/mirai-console-loader
 21:30:11 [INFO] This program is licensed under GNU AGPL v3
 21:30:11 [DEBUG] Loading script: boot.js
 21:30:11 [DEBUG] Loading script: config.js
 21:30:11 [DEBUG] Loading script: repo.js
 21:30:11 [DEBUG] Loading script: updater.js
 21:30:12 [INFO] Verifying "net.mamoe:mirai-console" version 1.0.0
 21:30:13 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 1.0.0
 21:30:13 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.1
2020-11-23 21:30:15 I/main: Starting mirai-console...
2020-11-23 21:30:15 I/main: Backend: version 1.0.0, built on 2020-11-20 11:45:09.
2020-11-23 21:30:15 I/main: Frontend Terminal: version 1.0.0, provided by Mamoe Technologies
2020-11-23 21:30:15 I/plugin: Successfully loaded plugin MiraiNative
2020-11-23 21:30:15 I/plugin: Successfully loaded plugin OneBot
2020-11-23 21:30:15 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-11-23 21:30:15 I/MiraiNative: 正在加载 Mirai Native Bridge E:\test\mcl\data\MiraiNative\CQP.dll
2020-11-23 21:30:16 E/MiraiNative: java.lang.NoSuchMethodError: 'void net.mamoe.mirai.console.command.CompositeCommand.<init>(net.mamoe.mirai.console.command.CommandOwner, java.lang.String, java.lang.String[], java.lang.String, net.mamoe.mirai.console.permission.Permission, boolean, net.mamoe.mirai.console.command.description.CommandArgumentContext, int, kotlin.jvm.internal.DefaultConstructorMarker)'
java.lang.NoSuchMethodError: 'void net.mamoe.mirai.console.command.CompositeCommand.<init>(net.mamoe.mirai.console.command.CommandOwner, java.lang.String, java.lang.String[], java.lang.String, net.mamoe.mirai.console.permission.Permission, boolean, net.mamoe.mirai.console.command.description.CommandArgumentContext, int, kotlin.jvm.internal.DefaultConstructorMarker)'
        at org.itxtech.mirainative.manager.PluginManager$NpmCommand.<init>(PluginManager.kt:210)
        at org.itxtech.mirainative.manager.PluginManager$NpmCommand.<clinit>(PluginManager.kt:210)
        at org.itxtech.mirainative.manager.PluginManager.registerCommands(PluginManager.kt:338)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:168)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:111)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:113)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:169)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:213)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:201)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
```

**运行环境**
 - 操作系统：win10 家庭中文版 20H2 (19042.630)
 - `mirai core` 版本：1.3.1
 - `mirai console` 版本：1.0.0
 - `mirai native` 版本：1.9.3
 - `Java` 运行时版本：jre 11.0.7 x86

**更多信息**
用隔壁的[onebot-kotlin](https://github.com/yyuueexxiinngg/onebot-kotlin)也加载失败

**Comment by PeratX** [comment]
在做了在做了

**Comment by PeratX** [comment]
已發佈 1.9.4
