### ISSUE TITLE
C++运行库 2015-2019无法启动MiraiNative

### ISSUE THREAD

**Issue by Hero-awa** [iTXTech/mirai-native#113]
您好，我正在使用MiraiNative，并碰到了一些问题。
首先，如题。我无法确定MiraiNative所依赖的运行库。如果我使用C++ 2015-2019 x86 & x64，将有部分coolq应用出现异常/无法打开。
但是如果我使用了仅包含了2019 x86 & x64版本的C++库，MiraiNative将在使用较长一段时间后无法加载插件。
望您能在readme中写出依赖库或者提供一些用户的自救方法，万分感谢！

**Comment by PeratX** [comment]
# 请按照issue模板提交

* `MiraiNative`不依赖运行库，默认已经打包进去了

**Comment by Hero-awa** [comment]
那…早期能够加载的插件在一段时间后无法加载，是什么原因造成的qwq
因为我将机器人用在云服务器上，快速重装后可以正常加载插件。

**Comment by PeratX** [comment]
那我也不知道……

**Comment by Hero-awa** [comment]
github我认识也不多，可能为您造成不便，请谅解！
怎么上传截图qwq 虽然可能没有解决方法，但是我也算是反馈一个玄学问题叭
（第一次在github找到能够实时交流的活人，有点激动

**Comment by PeratX** [comment]
ctrl-c + ctrl-v 直接粘贴即可

**Comment by Hero-awa** [comment]
13:45:41 [INFO] Mirai Console Loader version 1.0.2-a374eff
 13:45:41 [INFO] https://github.com/iTXTech/mirai-console-loader
 13:45:41 [INFO] This program is licensed under GNU AGPL v3
 13:45:41 [DEBUG] Loading script: boot.js
 13:45:41 [DEBUG] Loading script: config.js
 13:45:41 [DEBUG] Loading script: repo.js
2020-12-05 13:45:43 I/main: Starting mirai-console...
2020-12-05 13:45:43 I/main: Backend: version 1.0-RC-dev-28, built on 2020-09-21
12:37:02.
2020-12-05 13:45:43 I/main: Frontend Terminal: version 1.0-RC-dev-28, provided b
y Mamoe Technologies
2020-12-05 13:45:43 V/main: Loading configurations...
2020-12-05 13:45:44 V/main: Loading JVM plugins...
2020-12-05 13:45:44 I/plugin: Successfully loaded plugin MiraiNative
2020-12-05 13:45:44 V/main: 0 external PluginLoader(s) found.
2020-12-05 13:45:44 V/main: 1 plugin(s) loaded.
2020-12-05 13:45:44 V/main: Loading PermissionService...
2020-12-05 13:45:44 V/main: Reloaded PermissionService settings.
2020-12-05 13:45:44 V/main: Loading built-in commands...
2020-12-05 13:45:44 V/main: Prepared built-in commands: help, login, permission,
 stop
2020-12-05 13:45:44 V/main: Enabling plugins...
2020-12-05 13:45:45 E/MiraiNative: kotlinx.serialization.json.internal.JsonDecod
ingException: Unexpected JSON token at offset 0: Expected '{, kind: CLASS'
JSON input:
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token
 at offset 0: Expected '{, kind: CLASS'
JSON input:
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingExce
ption(JsonExceptions.kt:30)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:329
)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructu
re(StreamingJsonDecoder.kt:46)
        at org.itxtech.mirainative.util.Configuration$$serializer.deserialize(Co
nfiguration.kt)
        at org.itxtech.mirainative.util.Configuration$$serializer.deserialize(Co
nfiguration.kt:89)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:62)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:40)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at org.itxtech.mirainative.util.ConfigMan$config$2.invoke(Configuration.
kt:43)
        at org.itxtech.mirainative.util.ConfigMan$config$2.invoke(Configuration.
kt:34)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.itxtech.mirainative.util.ConfigMan.getConfig(Configuration.kt)
        at org.itxtech.mirainative.ui.Tray$update$1$5$1.invoke(Tray.kt:109)
        at org.itxtech.mirainative.ui.Tray.update(Tray.kt:110)
        at org.itxtech.mirainative.ui.Tray.create(Tray.kt:57)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:159)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnE
nable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.en
able(BuiltInJvmPluginLoaderImpl.kt:100)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:
129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLo
adedPlugins$mirai_console(PluginManagerImpl.kt:169)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS
tart$mirai_console(MiraiConsoleImplementationBridge.kt:191)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi
raiConsoleImplementation.kt:194)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira
iConsoleTerminalLoader.kt:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22
6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169
2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357
8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j
ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap
ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:
105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j
ava:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101
)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)

2020-12-05 13:45:45 I/MiraiNative: 正在加载 Mirai Native Bridge C:\Users\Adminis
trator\Desktop\Minecraft-Server\the_Mirai_and_the_Naive\.\data\MiraiNative\CQP.d
ll
2020-12-05 13:45:45 I/MiraiNative: 正在加载外部库 C:\Users\Administrator\Desktop
\Minecraft-Server\the_Mirai_and_the_Naive\.\data\MiraiNative\libraries\libiconv.
dll
2020-12-05 13:45:45 I/MiraiNative: 正在加载外部库 C:\Users\Administrator\Desktop
\Minecraft-Server\the_Mirai_and_the_Naive\.\data\MiraiNative\libraries\sqlite3.d
ll
2020-12-05 13:45:45 I/MiraiNative: 插件 Naive.dll 已被加载，返回值为 0 。
2020-12-05 13:45:45 E/MiraiNative: Exception in coroutine Plugin MiraiNative of
MiraiNative
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token
 at offset 0: Expected '{, kind: CLASS'
JSON input:
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingExce
ption(JsonExceptions.kt:30)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:329
)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructu
re(StreamingJsonDecoder.kt:46)
        at org.itxtech.mirainative.util.Configuration$$serializer.deserialize(Co
nfiguration.kt)
        at org.itxtech.mirainative.util.Configuration$$serializer.deserialize(Co
nfiguration.kt:89)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:62)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:40)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at org.itxtech.mirainative.util.ConfigMan$config$2.invoke(Configuration.
kt:43)
        at org.itxtech.mirainative.util.ConfigMan$config$2.invoke(Configuration.
kt:34)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.itxtech.mirainative.util.ConfigMan.getConfig(Configuration.kt)
        at org.itxtech.mirainative.bridge.NativeBridge.updateInfo(NativeBridge.k
t:84)
        at org.itxtech.mirainative.manager.PluginManager.loadPlugin(PluginManage
r.kt:139)
        at org.itxtech.mirainative.manager.PluginManager$readPlugin$2.invokeSusp
end(PluginManager.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executo
rs.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledF
utureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

2020-12-05 13:45:45 I/main: 1 plugin(s) enabled.
2020-12-05 13:45:45 I/main: Auto-login 2181451553
2020-12-05 13:45:45 I/Bot 2181451553: Logging in...
2020-12-05 13:45:46 I/Bot 2181451553: Login successful
2020-12-05 13:45:46 I/main: mirai-console started successfully.
2020-12-05 13:45:46 E/MiraiNative: Exception in coroutine Plugin MiraiNative of
MiraiNative
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token
 at offset 0: Expected '{, kind: CLASS'
JSON input:
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingExce
ption(JsonExceptions.kt:30)
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:329
)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructu
re(StreamingJsonDecoder.kt:46)
        at org.itxtech.mirainative.util.Configuration$$serializer.deserialize(Co
nfiguration.kt)
        at org.itxtech.mirainative.util.Configuration$$serializer.deserialize(Co
nfiguration.kt:89)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableV
aluePolymorphic(Polymorphic.kt:62)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerial
izableValue(StreamingJsonDecoder.kt:40)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at org.itxtech.mirainative.util.ConfigMan$config$2.invoke(Configuration.
kt:43)
        at org.itxtech.mirainative.util.ConfigMan$config$2.invoke(Configuration.
kt:34)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.itxtech.mirainative.util.ConfigMan.getConfig(Configuration.kt)
        at org.itxtech.mirainative.util.ConfigMan.init(Configuration.kt:50)
        at org.itxtech.mirainative.MiraiNative$setBotOnline$1.invokeSuspend(Mira
iNative.kt:91)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executo
rs.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledF
utureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

>
________________________________
发件人: PeratX <notifications@github.com>
发送时间: 2020年12月5日 13:29
收件人: iTXTech/mirai-native <mirai-native@noreply.github.com>
抄送: Hero-awa <dolphin455@outlook.com>; Author <author@noreply.github.com>
主题: Re: [iTXTech/mirai-native] C++运行库 2015-2019无法启动MiraiNative (#113)


ctrl-c + ctrl-v 直接粘贴即可

―

**Comment by PeratX** [comment]
JSON文件内禁止含有注释

**Comment by Hero-awa** [comment]
奇奇怪怪的，我在11月21日时依然能正常使用插件
但是在12月1日重启系统后就出现了报错
Mirai 版本:1.3.3
JDK 版本:1.15 x86
Windows 版本:Server 2012 R2 Datacenter
（版本号我就只记得个大概）
________________________________
发件人: PeratX <notifications@github.com>
发送时间: 2020年12月5日 13:47
收件人: iTXTech/mirai-native <mirai-native@noreply.github.com>
抄送: Hero-awa <dolphin455@outlook.com>; Author <author@noreply.github.com>
主题: Re: [iTXTech/mirai-native] C++运行库 2015-2019无法启动MiraiNative (#113)


JSON文件内禁止含有注释

―

**Comment by Hero-awa** [comment]
![Screenshot_2020-11-21-15-54-16-711_com microsoft rdc android](https://user-images.githubusercontent.com/66959390/101236134-888b5c80-3709-11eb-90d4-b7537506d725.jpg)

**Comment by PeratX** [comment]
非常奇怪

**Comment by Hero-awa** [comment]
感谢您的耐心回答！
qwq
