### ISSUE TITLE
插件加载错误

### ISSUE THREAD

**Issue by liaosunny123** [iTXTech/mirai-native#127]
**描述这个Bug**
加载插件时出错，菜单出现了这个插件“已禁用”和“已加载”且无法启用
**复现步骤**
加载这个插件
**期望的行为**
插件被正常加载

**截图和日志**
您必须提交相应的截图和 mirai console 日志
console:
2021-02-03 22:53:04 E/MiraiNative: java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
        at org.itxtech.mirainative.manager.EventManager.registerEvents(EventManager.kt:264)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:169)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:204)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.event.Listener$ConcurrencyKind
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 13 more

**运行环境**
 - 操作系统：Windows 10 1909
 - `mirai core` 版本：2.1.0
 - `mirai console` 版本：2.0.0
 - `mirai native` 版本：2.0.0
 - `Java` 运行时版本：15.0.2 x86

**Comment by PeratX** [comment]
mirai native目前没有发布2.0.0版本，请检查是否使用了`2.0.0-beta.1`

**Comment by liaosunny123** [comment]
好的，感谢，是我的疏忽
