### ISSUE TITLE
mirai-native加载出错

### ISSUE THREAD

**Issue by Samarium150** [iTXTech/mirai-native#131]
**描述这个Bug**
mcl加载mirai-native报错
mirai-native加载http报错

**复现步骤**
- 1. `.\mcl.cmd --update-package org.itxtech:mirai-native --channel stable --type plugin`
- 2. 使用AdoptOpenJDK 15启动mcl

**期望的行为**
mirai-native正常加载

**截图和日志**
```
2021-02-25 09:09:56 I/MiraiNative: 插件 http.dll 已被加载，返回值为 0 。
2021-02-25 09:09:56 W/MiraiNative: 无法找到 http.dll 的插件信息。
2021-02-25 09:09:56 E/MiraiNative: java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
        at org.itxtech.mirainative.manager.EventManager.registerEvents(EventManager.kt:264)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:169)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:202)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.event.Listener$ConcurrencyKind
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 41 more
```
![image](https://user-images.githubusercontent.com/28302241/109166381-a5549080-774a-11eb-9198-10f32e5fcfd4.png)
![image](https://user-images.githubusercontent.com/28302241/109166427-b00f2580-774a-11eb-8da7-d38ccd213a7c.png)

**运行环境**
 - 操作系统：Windows 10 企业版 20H2 19042.804
 - `mirai core` 版本：2.4.0
 - `mirai console` 版本：2.4.0
 - `mirai native` 版本：1.9.6
 - `Java` 运行时版本：[AdoptOpenJDK 15 x86](https://adoptopenjdk.net/)

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
.\mcl.cmd --update-package org.itxtech:mirai-native --channel beta --type plugin

**Comment by PeratX** [comment]
对了http.json内的注释要删掉

**Comment by Samarium150** [comment]
感谢
