### ISSUE TITLE
Mirai Console Loader中加载插件失败 已登录状态却返回“bot未登陆”

### ISSUE THREAD

**Issue by Eigh18n** [iTXTech/mirai-native#137]
**描述这个Bug**
使用`Mirai Console Loader`时，能够正常加载插件，但是启动插件时却返回“Bot 还未上线，无法调用 Enable 事件。”

**复现步骤**
使用`Mirai Console Loader`启动`mirai-console`和`mirai-core`，在加载时有报错，但是不影响正常启动，随后使用`login`手动登陆也为正常，但是使用`npm enable`启动插件时，却返回“Bot 还未上线，无法调用 Enable 事件。”

**期望的行为**
正常启动native插件

**截图和日志**
报错信息：
```sh
2021-04-10 20:05:58 E/MiraiNative: java.lang.NoClassDefFoundError: net/mamoe/mir
ai/event/Listener$ConcurrencyKind
java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
        at org.itxtech.mirainative.manager.EventManager.registerEvents(EventMana
ger.kt:264)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:169)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnE
nable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.en
able(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(Jvm
PluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManag
er.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLo
adedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doS
tart$mirai_console(MiraiConsoleImplementationBridge.kt:208)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(Mi
raiConsoleImplementation.kt:277)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDa
emon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(Mira
iConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknow
n Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:22
6)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:169
2)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:4
12)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:357
8)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.j
ava:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.j
ava:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdap
ter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:
105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.j
ava:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101
)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.event.Listener$Conc
urrencyKind
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClas
s$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClas
s(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 41 more
```

启动失败日志：
```sh
2021-04-10 20:05:58 I/main: 2 plugin(s) enabled.
2021-04-10 20:05:58 I/MiraiNative: 插件 MengCustom.dll 已被加载，返回值为 0 。
2021-04-10 20:05:58 I/main: mirai-console started successfully.
> login 22**** ***
2021-04-10 20:06:35 I/Bot.22***: Logging in...
2021-04-10 20:06:37 I/Bot.22***: No OtherClient online.
2021-04-10 20:06:46 I/Bot.22***: Login successful
 (22***) Login successful
> npm enable 0
Bot 还未上线，无法调用 Enable 事件。
```

**运行环境**
 - 操作系统：[例子：Windows server 2012 R2 datacenter]
 - `mirai core` 版本：2.6-M2
 - `mirai console` 版本：2.6-M2
 - `mirai native` 版本：1.9.6
 - `Java` 运行时版本：11.0.10

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by Eigh18n** [comment]
不小心交了两次（x）
