### ISSUE TITLE
mcl中尝试启动native插件失败

### ISSUE THREAD

**Issue by Eigh18n** [iTXTech/mirai-native#138]
**描述这个Bug**
使用`Mirai Console Loader`时，能够正常加载插件，但是启动插件时却返回“Bot 还未上线，无法调用 Enable 事件。”

**复现步骤**
使用`Mirai Console Loader`启动`mirai-console`和`mirai-core`，在加载时有报错，但是不影响正常启动，随后使用`login`手动登陆也为正常，但是使用`npm enable`启动插件时，却返回“Bot 还未上线，无法调用 Enable 事件。”

**期望的行为**
正常启动native插件

**截图和日志**
报错信息：
```sh
2021-04-10 20:05:58 E/MiraiNative: java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
java.lang.NoClassDefFoundError: net/mamoe/mirai/event/Listener$ConcurrencyKind
        at org.itxtech.mirainative.manager.EventManager.registerEvents(EventManager.kt:264)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:169)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:208)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:277)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.event.Listener$ConcurrencyKind
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 41 more
```

启动失败日志：
```sh
2021-04-10 20:05:58 I/main: 2 plugin(s) enabled.
2021-04-10 20:05:58 I/MiraiNative: 插件 MengCustom.dll 已被加载，返回值为 0 。
2021-04-10 20:05:58 I/main: mirai-console started successfully.
> login 22**** ***
2021-04-10 20:06:35 I/Bot.22***: Logging in...
2021-04-10 20:06:37 I/Bot.22***: No OtherClient online.
2021-04-10 20:06:46 I/Bot.22***: Login successful
 (22***) Login successful
> npm enable 0
Bot 还未上线，无法调用 Enable 事件。
```

**运行环境**
 - 操作系统：[例子：Windows server 2012 R2 datacenter]
 - `mirai core` 版本：2.6-M2
 - `mirai console` 版本：2.6-M2
 - `mirai native` 版本：1.9.6
 - `Java` 运行时版本：11.0.10

**更多信息**
我看过#85 但是自动登录我还是同样的情况。
而且我在native文件下添加了libraries目录，该目录下文件在native1.9.2-7版本中可正常运行，或许是我画蛇添足？

**Comment by PeratX** [comment]
用 2.0.0-beta版本即可
