### ISSUE TITLE
native无法解析.net API的SendGroupMessage方法

### ISSUE THREAD

**Issue by CBGan** [iTXTech/mirai-native#14]
所使用酷Q API ：Native.Framework
出错的函数：SendGroupMessage
-------------------------------------------------
Exception in thread "DefaultDispatcher-worker-2" Exception in thread "DefaultDispatcher-worker-7" java.util.NoSuchElementException: group [QQ群群号]
        at net.mamoe.mirai.Bot.getGroup(Bot.kt:178)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
java.util.NoSuchElementException: group [QQ群群号]
        at net.mamoe.mirai.Bot.getGroup(Bot.kt:178)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by PeratX** [comment]
可能的问题：该QQ不在那个群里面

**Comment by CBGan** [comment]
不是QQ的问题，是不能发送群组消息

**Comment by PeratX** [comment]
我给一个不存在的群发消息会是这样的提示
```
Exception in thread "DefaultDispatcher-worker-5" java.util.NoSuchElementException: group 1252
        at net.mamoe.mirai.Bot.getGroup(Bot.kt:178)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
请问您有没有换一个QQ试试？

**Comment by CBGan** [comment]
换过了一样的错误

**Comment by PeratX** [comment]
请确认当前QQ在那个群里面。

**Comment by CBGan** [comment]
在的

**Comment by PeratX** [comment]
请向mirai汇报该问题，该错误于本项目无关。

**Comment by PeratX** [comment]
请问您的mirai core版本是？

**Comment by CBGan** [comment]
core版本1.1.3
mirai已经停止维护了（

**Comment by PeratX** [comment]
这个问题看了下已经修复了，请静候新版本，或者尝试重开mirai解决问题（雾

**Comment by CBGan** [comment]
好的谢谢
