### ISSUE TITLE
在使用自动撤回时报错

### ISSUE THREAD

**Issue by 502milk** [iTXTech/mirai-native#148]
使用最新代码构建的版本，自动撤回的内如会导致一次报错，报错后再无撤回动作

日志
E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalArgumentException: Failed requirement.
        at net.mamoe.mirai.internal.network.protocol.packet.chat.PbMessageSvc$PbMsgWithDraw.createForGroupMessage(PbMessageSvc.kt:54)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.PbMessageSvc$PbMsgWithDraw.createForGroupMessage$default(PbMessageSvc.kt:47)
        at net.mamoe.mirai.internal.MiraiImpl.recallMessage$suspendImpl(MiraiImpl.kt:475)
        at net.mamoe.mirai.internal.MiraiImpl.recallMessage(MiraiImpl.kt)
        at net.mamoe.mirai.message.data.MessageSource$Key.recall(MessageSource.kt:209)
        at org.itxtech.mirainative.manager.CacheManager$recall$1.invokeSuspend(CacheManager.kt:112)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**运行环境**
 - 操作系统：win server 2012R2
 - `mirai core` 版本：2.7.1-dev-1
 - `mirai console` 版本：2.7.1-dev-1
 - `mirai native` 版本：最新代码构建
 - `Java` 运行时版本：AdoptOpenJDK 15.0.2

**Comment by PeratX** [comment]
请升级到最新版尝试
