### ISSUE TITLE
踢群成员功能失效

### ISSUE THREAD

**Issue by KinomotoKi** [iTXTech/mirai-native#151]
**描述这个Bug**
　　我是用mirai机器人装了酷Q插件然后在酷Q下使用原先酷Q的插件运行的，原先酷Q的踢人功能以前一切正常，有段时间没有使用此功能了，今天再次使用此功能时，出现了以下错误，群成员并未被踢出群，似乎该功能失效了，我不太清楚具体是哪一环节出现的问题，猜测可能与mirai升级至2.7.1有关？

-----
**复现步骤**
1. 触发原先酷Q插件内的移除群员功能，并收到插件回应已提出的文本
2. 检查群成员，发现此人并未被踢出

-----
**初步判断**
　　此问题在mirai升级至2.7.1后出现，初步判断从插件到native的CQP.dll是OK的，问题应该出在native和最新版mirai交互的过程中。

-----
**期望的行为**
　　正常移除该群员

-----
**日志**
```
2021-12-26 14:48:14 E/MiraiNative: Exception in coroutine Plugin org.itxtech.mirainative of MiraiNative
java.lang.NullPointerException: Parameter specified as non-null is null: method org.itxtech.mirainative.Bridge.setGroupKick, parameter message
        at org.itxtech.mirainative.Bridge.setGroupKick(Bridge.kt)
        at org.itxtech.mirainative.Bridge.pEvPrivateMessage(Native Method)
        at org.itxtech.mirainative.bridge.NativeBridge.eventPrivateMessage(NativeBridge.kt:126)
        at org.itxtech.mirainative.manager.EventManager$registerEvents$1$3$1.invokeSuspend(EventManager.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

-----
**运行环境**
 - 操作系统：windows server 2019
 - `iTXTech Mirai Console Loader` version 1.0.5-9b6cf6d
 - `net.mamoe:mirai-console` version 2.9.0-RC2
 - `net.mamoe:mirai-console-terminal` version 2.9.0-RC2
 - `net.mamoe:mirai-core-all` version 2.9.0-RC2
 - `org.itxtech:mirai-native` version 2.0.0-beta.1
 - `Java` 运行时版本：ZuluOpenJDK11.48.21 x86
 - `CQP.dll`版本：2.0.0.19

**Comment by KinomotoKi** [comment]
**此次之前的两次运行踢人功能时的配置：**

----

**时间：2021年6月1日**

程序信息：
[INFO] iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
[INFO] "net.mamoe:mirai-console" version 2.6.4
[INFO] "net.mamoe:mirai-console-terminal" version 2.6.4
[INFO] "net.mamoe:mirai-core-all" version 2.6.4
[INFO] "org.itxtech:mirai-native" version 1.9.6

插件：
CQP.dll

----

**时间：2021年8月2日**

程序信息：
[INFO] iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
[INFO] "net.mamoe:mirai-console" version 2.7-M2
[INFO] "net.mamoe:mirai-console-terminal" version 2.7-M2
[INFO] "net.mamoe:mirai-core-all" version 2.7-M2
[INFO] "org.itxtech:mirai-native" version 2.0.0-beta.1

插件：
CQP.dll

**Comment by x5violet** [comment]
最新的2.0.3版本开始不踢人了，希望能修复下

**Comment by KinomotoKi** [comment]
**最新状态：**更新到CQP.dll 2.0.0.19后，jvm不崩溃了，但是踢人没有反应，人踢不掉，有以下错误报出：

2021-12-26 14:48:14 E/MiraiNative: Exception in coroutine Plugin org.itxtech.mirainative of MiraiNative
java.lang.NullPointerException: Parameter specified as non-null is null: method org.itxtech.mirainative.Bridge.setGroupKick, parameter message
        at org.itxtech.mirainative.Bridge.setGroupKick(Bridge.kt)
        at org.itxtech.mirainative.Bridge.pEvPrivateMessage(Native Method)
        at org.itxtech.mirainative.bridge.NativeBridge.eventPrivateMessage(NativeBridge.kt:126)
        at org.itxtech.mirainative.manager.EventManager$registerEvents$1$3$1.invokeSuspend(EventManager.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

-----
**时间：2021年12月26日**

程序信息：
[INFO]  iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
[INFO] "net.mamoe:mirai-console" version 2.9.0-RC2
[INFO] "net.mamoe:mirai-console-terminal" version 2.9.0-RC2
[INFO] "net.mamoe:mirai-core-all" version 2.9.0-RC2
[INFO] "org.itxtech:mirai-native" version 2.0.0-beta.1

插件：
CQP.dll 2.0.0.19

**Comment by KinomotoKi** [comment]
目前还是无法踢人，希望能修复下

**Comment by 502milk** [comment]
用mirai2.7M1及以下版本
能用就别更新

**Comment by KinomotoKi** [comment]
> 用mirai2.7M1及以下版本 能用就别更新

老版本踢人现在是永久踢出Q群，会默认拒绝再次加入，就因为这个bug才升级的，升级后发现踢人jvm就崩，检查是因为CQP.dll是1.9的旧版本，升级CQP.dll到2.0后，jvm不崩了，但是踢人失效，无法解决，所以才来反馈此问题

**Comment by PeratX** [comment]
咕咕

**Comment by KinomotoKi** [comment]
> 咕咕

噗...大神新年快乐呀~
可千万别咕呀~T_T

**Comment by PeratX** [comment]
已发布2.0.0
