### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by haha-dream** [iTXTech/mirai-native#170]
**描述这个Bug**
正常运行时崩溃，第一次重启时与petpet冲突抛出错误，随后无法再次重启

**复现步骤**
因为是正常运行时报错所以暂时无法找到复现方法

**期望的行为**
MiraiNative正常载入并加载插件

**截图和日志**
`与petpet冲突`
> 2022-12-04 15:24:51 E/MiraiNative: Exception in coroutine Plugin org.itxtech.mirainative of MiraiNative
java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.callIntMethod(Native Method)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.bridge.NativeBridge.enablePlugin(NativeBridge.kt:258)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.manager.PluginManager.enablePlugin(PluginManager.kt:178)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.manager.PluginManager$enablePlugins$1.invokeSuspend(PluginManager.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-12-04 15:24:51 W/stderr: Exception in thread "Thread-17" java.lang.NullPointerException
2022-12-04 15:24:51 W/stderr: 	at java.base/java.util.Objects.requireNonNull(Unknown Source)
2022-12-04 15:24:51 W/stderr: 	at petpet-5.0.mirai2.jar//moe.dituon.petpet.plugin.DataUpdater.checkUpdate(DataUpdater.java:63)
2022-12-04 15:24:51 W/stderr: 	at petpet-5.0.mirai2.jar//moe.dituon.petpet.plugin.DataUpdater.autoUpdate(DataUpdater.java:21)
2022-12-04 15:24:51 W/stderr: 	at java.base/java.lang.Thread.run(Unknown Source)
2022-12-04 15:24:51 W/stderr: Exception in thread "Thread-23" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 15:24:51 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
2022-12-04 15:24:52 W/stderr: Exception in thread "Thread-24" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 15:24:52 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
2022-12-04 15:24:52 W/stderr: Exception in thread "Thread-25" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 15:24:52 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
2022-12-04 15:24:52 W/stderr: Exception in thread "Thread-26" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 15:24:52 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)

`后续报错`
> 2022-12-04 18:24:35 E/MiraiNative: Exception in coroutine Plugin org.itxtech.mirainative of MiraiNative
java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.callIntMethod(Native Method)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.bridge.NativeBridge.enablePlugin(NativeBridge.kt:258)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.manager.PluginManager.enablePlugin(PluginManager.kt:178)
	at mirai-native-2.0.1.jar//org.itxtech.mirainative.manager.PluginManager$enablePlugins$1.invokeSuspend(PluginManager.kt:200)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-12-04 18:24:35 W/stderr: Exception in thread "Thread-15" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 18:24:35 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
2022-12-04 18:24:36 W/stderr: Exception in thread "Thread-16" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 18:24:36 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
2022-12-04 18:24:36 W/stderr: Exception in thread "Thread-17" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 18:24:36 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)
2022-12-04 18:24:36 W/stderr: Exception in thread "Thread-18" java.lang.NoClassDefFoundError: Could not initialize class org.itxtech.mirainative.bridge.MiraiBridge
2022-12-04 18:24:36 W/stderr: 	at mirai-native-2.0.1.jar//org.itxtech.mirainative.Bridge.addLog(Bridge.kt:176)

**运行环境**
 - 操作系统：Windows 10 21H2
 - `mirai core` 版本：2.13.0
 - `mirai console` 版本：2.13.0
 - `mirai native` 版本：2.0.1
 - `Java` 运行时版本：17.0.5 x86

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
重试下载mirai native尝试
