### ISSUE TITLE
无法正常启动/加载插件

### ISSUE THREAD

**Issue by timeance** [iTXTech/mirai-native#175]
**描述这个Bug**
尝试了各种版本的mirai和插件，均无法正常启动或者加载插件后崩溃

**复现步骤**

**期望的行为**
能够在mirai 2.13版本及以上正常运行

**截图和日志**
 - 操作系统：winser 2019
 - `mirai core` 版本：2.13
 - `mirai native` 版本：2.0.1
 - `Java` 运行时版本：11.07 x86
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x5c8067b6, pid=693324, tid=410748
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)
# Java VM: OpenJDK Client VM AdoptOpenJDK (11.0.8+10, mixed mode, serial gc, windows-x86)
# Problematic frame:
# V  [jvm.dll+0x867b6]
#
# Core dump will be written. Default location: C:\Users\Administrator\Desktop\Bot_zar\Mirai-mcl-new\hs_err_pid693324.mdmp
#
# An error report file with more information is saved as:
# C:\Users\Administrator\Desktop\Bot_zar\Mirai-mcl-new\hs_err_pid693324.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
Process exited with -1073740791
```
---

当使用java16之后...
 - `mirai core` 版本：2.13
 - `mirai native` 版本：2.0.1
 - `Java` 运行时版本：16 x86
```
# A fatal error has been detected by the Java Runtime Environment:
#
#
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x5c6f5fd6, pid=49500, tid=472580
#
# JRE version: OpenJDK Runtime Environment Temurin-16.0.2+7 (16.0.2+7) (build 16.0.2+7)
# Java VM: OpenJDK Client VM Temurin-16.0.2+7 (16.0.2+7, mixed mode, serial gc, windows-x86)
# Problematic frame:
  [jvm.dll+0x5fd6]

```
---

当使用 #173 里的修改版后，一旦触发cq插件就会崩溃
```
2023-03-11 01:30:35 E/MiraiNative: Exception in coroutine Plugin org.itxtech.mirainative of MiraiNative
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:150)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:50)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**运行环境**
 - 操作系统：winser 2019
 - `mirai core` 版本：2.13
 - `mirai console` 版本：2.13
 - `mirai native` 版本：2.13
 - `Java` 运行时版本：11.07 x86

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by timeance** [comment]
破案了，原来是QQ号被临时封锁，部分群无法发送消息。

现在运行良好：
 - `mirai core` 版本：2.14.0
 - `mirai native` 版本：2.0.0 #173 版本
 - `Java` 运行时版本：11
