### ISSUE TITLE
Can't find dependent libraries 无法找到依赖

### ISSUE THREAD

**Issue by dogdie233** [iTXTech/mirai-native#20]
报错信息
```
 23:21:58 [INFO] [Plugin Manager] java.lang.UnsatisfiedLinkError: C:\Users\Administrator\Desktop\mirai_for_bilibili\plugins\MiraiNative\CQP.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1088)
        at org.itxtech.mirainative.manager.LibraryManager.load(LibraryManager.kt:33)
        at org.itxtech.mirainative.MiraiNative.checkNativeLibs(MiraiNative.kt:55)
        at org.itxtech.mirainative.MiraiNative.onEnable(MiraiNative.kt:112)
        at net.mamoe.mirai.console.plugins.PluginBase.enable$mirai_console(PluginBase.kt:144)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPluginsImpl$mirai_console(PluginManager.kt:334)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:79)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins$default(PluginManager.kt:79)
        at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:131)
        at net.mamoe.mirai.console.MiraiConsole.start$default(MiraiConsole.kt:113)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.mamoe.mirai.console.wrapper.WrapperMain.start$mirai_console_wrapper(WrapperMain.kt:236)
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative$mirai_console_wrapper(WrapperMain.kt:207)
        at net.mamoe.mirai.console.wrapper.WrapperCli.run(WrapperMain.kt:143)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:176)

 23:21:58 [INFO] [Plugin Manager] MiraiNative failed to enable, disabling it
 23:21:58 [INFO] [Plugin Manager] MiraiNative 推荐立即删除/替换并重启
 23:21:58 [INFO] [Plugin Manager] 加载了0个插件
 ```
还有什么依赖要装的吗...

**Comment by PeratX** [comment]
是否使用最新的MiraiNative1.8.2？

**Comment by dogdie233** [comment]
1.7.0 我换成新版本试试

**Comment by dogdie233** [comment]
换了1.8.2，然后把CQP.dll删掉，能用了，感谢
