### ISSUE TITLE
在Linux下运行mirai时加载mirai-native报错

### ISSUE THREAD

**Issue by MemorySnow** [iTXTech/mirai-native#22]
12:44:49 [INFO] [Plugin Manager] 开始加载/home/mirai/plugins/下的插件
 12:44:49 [INFO] [Plugin Manager] loading plugin MiraiNative
 12:44:49 [INFO] [Plugin Manager] successfully loaded plugin MiraiNative version 1.8.2 by iTX Technologies
 12:44:49 [INFO] [Plugin Manager] 强大的 Mirai 原生插件加载器
 12:44:49 [INFO] [Plugin Manager] java.lang.ExceptionInInitializerError
        at org.itxtech.mirainative.MiraiNative.onLoad(MiraiNative.kt:90)
        at net.mamoe.mirai.console.plugins.PluginBase.load$mirai_console(PluginBase.kt:137)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPluginsImpl$mirai_console(PluginManager.kt:319)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:79)
        at net.mamoe.mirai.console.plugins.PluginManager.reloadPlugins(PluginManager.kt:73)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$8$1.invokeSuspend(DefaultCommands.kt:310)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$8$1.invoke(DefaultCommands.kt)
        at net.mamoe.mirai.console.command.AnonymousCommand.onCommand(Command.kt:122)
        at net.mamoe.mirai.console.command.CommandManager.processCommandImpl(CommandManager.kt:157)
        at net.mamoe.mirai.console.command.CommandManager$processCommand$2.invokeSuspend(CommandManager.kt:147)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
        at java.awt.Window.<init>(Unknown Source)
        at java.awt.Frame.<init>(Unknown Source)
        at javax.swing.JFrame.<init>(Unknown Source)
        at org.itxtech.mirainative.ui.FloatingWindow.<clinit>(FloatingWindow.kt:40)
        ... 15 more

 12:44:49 [INFO] [Plugin Manager] MiraiNative failed to load, disabling it
 12:44:49 [INFO] [Plugin Manager] MiraiNative 推荐立即删除/替换并重启
 12:44:49 [INFO] [Plugin Manager] 加载了0个插件

**Comment by MemorySnow** [comment]
环境Centos7，JAVA版本Java(TM) SE Runtime Environment (build 1.8.0_261-b12)

**Comment by PeratX** [comment]
mirainative不支持linux环境，请使用wine环境运行

**Comment by MemorySnow** [comment]
好的
