### ISSUE TITLE
发送长消息或消息内带有某些新[CQ:face]时出错

### ISSUE THREAD

**Issue by zxin8580** [iTXTech/mirai-native#31]
报错信息放到了图床
https://p.pstatp.com/origin/ff40000283bc81f5ebc5
https://p.pstatp.com/origin/ff40000283be06bc6342
是native本身的异常导致的吗

**Comment by PeratX** [comment]
某些新[CQ:face]请具体
请给出发送的消息原文。

**Comment by zxin8580** [comment]
-> [mirai:source:3257,-816099952]#读617663588
 23:40:03 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 23:40:04 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
Exception in thread "DefaultDispatcher-worker-7" java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:63)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 23:40:09 [INFO] [NETWORK] Send: Heartbeat.Alive
 23:40:09 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response

源文件：https://uncle-siege.oss-cn-shanghai.aliyuncs.com/upload/617663588.ini

还有一个type34的比较难复现

**Comment by PeratX** [comment]
和开发团队沟通了一下，这个是mirai那边的问题，请到时向那边汇报问题

**Comment by PeratX** [comment]
团队回复：私聊不支持长消息

**Comment by PeratX** [comment]
type 34是服务器错误

**Comment by zxin8580** [comment]
> type 34是服务器错误

好的感谢，mirai和native已经帮上很大忙了

**Comment by PeratX** [comment]
> > type 34是服务器错误
> 
> 好的感谢，mirai和native已经帮上很大忙了

如果错误调用栈无法跟踪到mirainative，那就是mirai core的问题，请向mirai那边提交issue
