### ISSUE TITLE
现在还可以用吗？

### ISSUE THREAD

**Issue by liuzheng2000** [iTXTech/mirai-native#4]
我想用io.github.richardchien.coolqhttpapi，但是好像没有加载，不知道是不是我自己的问题

**Comment by PeratX** [comment]
请上传您的日志，运行环境，操作系统，以及mirai和插件版本和插件目录结构

**Comment by PeratX** [comment]
暂时关闭，如果能提供更多信息，会重新开启

**Comment by PeratX** [comment]
我会调查的

**Comment by takayama-lily** [comment]
cqhttp是最新的4.15版本
```
npm
 14:32:47 [INFO] [Command] npm [list|enable|disable|menu|info|load|unload] (插件 Id / 路径) (方法名)
npm list
 14:32:50 [INFO] [Command] 共加载了 0 个 Mirai Native 插件
npm load http
 14:33:02 [INFO] [Command] 文件 http 不存在
npm load http.dll
 14:33:17 [INFO] [Command] 文件 http.dll 不存在
npm load plugins/http.dll
Exception in thread "MiraiNative" java.lang.UnsatisfiedLinkError: org.itxtech.mirainative.Bridge.loadNativePlugin(Ljava/lang/String;I)I
        at org.itxtech.mirainative.Bridge.loadNativePlugin(Native Method)
        at org.itxtech.mirainative.bridge.NativeBridge.loadPlugin(NativeBridge.kt:44)
        at org.itxtech.mirainative.manager.PluginManager$loadPlugin$2.invokeSuspend(PluginManager.kt:110)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
