### ISSUE TITLE
在console 1.0-M3-1 无法正常加载该插件

### ISSUE THREAD

**Issue by zhzRedstone** [iTXTech/mirai-native#74]
**描述这个Bug**

在console 1.0-M3-1 无法正常加载该插件

**复现步骤**

更新console到1.0-M3-1
运行会生成个plugins目录和data目录
下载该插件，放到plugins目录里
运行console

**期望的行为**

可正常加载该插件

**日志**

```
2020-08-30 13:43:41 I/main: Starting mirai-console...
2020-08-30 13:43:41 I/main: Backend: version 1.0-M3-1, built on 2020-08-27 22:43:41.
2020-08-30 13:43:41 I/main: Frontend Pure: version 1.0-M3-1, provided by Mamoe Technologies
2020-08-30 13:43:41 I/main: Reloading configurations...
2020-08-30 13:43:42 I/main: Prepared built-in commands: help, login, managers, stop
2020-08-30 13:43:42 I/main: Loading plugins...
2020-08-30 13:43:42 I/plugin: Cannot load plugin MiraiNative
Exception in thread "main" java.lang.Throwable: init or load class error
        at net.mamoe.mirai.console.internal.plugin.PluginsLoader.loadPluginMainClassByJarFile(PluginsLoader.kt:67)
        at net.mamoe.mirai.console.internal.plugin.JarPluginLoaderImpl.load(JarPluginLoaderImpl.kt:87)
        at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.load(JarPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.load(JarPluginLoader.kt:35)
        at net.mamoe.mirai.console.plugin.DeferredPluginLoader.load(PluginLoader.kt:178)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:84)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAndEnableAllInOrder(PluginManagerImpl.kt:132)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadEnablePlugins$mirai_console(PluginManagerImpl.kt:127)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:102)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:118)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:53)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:52)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:40)
Caused by: java.lang.VerifyError: class org.itxtech.mirainative.MiraiNative overrides final method getDataFolder.()Ljava/io/File;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.mamoe.mirai.console.internal.plugin.AdaptiveURLClassLoader.loadClass(PluginsLoader.kt:109)
        at net.mamoe.mirai.console.internal.plugin.PluginsLoader.loadPluginMainClassByJarFile(PluginsLoader.kt:60)
        ... 12 more
请按任意键继续. . .
```

**运行环境**
 - 操作系统：[例子：Windows 7 旗舰版 build 7601]
 - `mirai core` 版本：[1.2.2]
 - `mirai console` 版本：[1.0-M3-1]
 - `mirai native` 版本：[1.9.0-rc.3]
 - `Java` 运行时版本：[1.8.0_252]

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/91652346-f00d8c80-eac8-11ea-9cfb-b262e887218c.png)
本版本不支持`console 1.0-M3-1`
