### ISSUE TITLE
cqhttp发送长消息失败报错

### ISSUE THREAD

**Issue by takayama-lily** [iTXTech/mirai-native#9]
300个汉字左右的消息
```
 15:46:20 [INFO] [MiraiNative] [CQHTTP HTTP] 已成功处理一个 API 请求：/send_private_msg
 15:46:20 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 15:46:21 [INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
Exception in thread "DefaultDispatcher-worker-4" java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:63)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by PeratX** [comment]
private不支持长消息
