### ISSUE TITLE
本地图片使用绝对路径无法正常发送

### ISSUE THREAD

**Issue by AdorableParker** [iTXTech/mirai-native#95]
**描述这个Bug**
根据文档中CQ码的支持说明，Native是支持本地图片绝对路径的图片CQ码的。
但我使用含本地绝对路径的CQ码时，无法成功发出消息，日志错误提示信息为空。

**复现步骤**

**期望的行为**
正常发送本地图片。

**截图和日志**
![image](https://user-images.githubusercontent.com/35246761/93715891-be0aba00-fb9e-11ea-8ed7-de889df1289b.png)
图中青色部分是我发送的CQ码，也是消息全文

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[例子：1.2.1]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0]
 - `Java` 运行时版本：[例子：11.0.7 x86]

**更多信息**

**Comment by AdorableParker** [comment]
今天发现发送网络图片也不得行。。。日志截图
![image](https://user-images.githubusercontent.com/35246761/93735505-a3245e00-fc0f-11ea-8c52-1af19e6afed2.png)
---
补充一些运行环境：
 `MiraiOK 20200915.071520 windows-386`
`Backend: version 1.0-M4, built on 2020-09-13 02:19:35`
`Frontend Pure: version 1.0-M4`

**Comment by PeratX** [comment]
> ## 今天发现发送网络图片也不得行。。。日志截图
> ![image](https://user-images.githubusercontent.com/35246761/93735505-a3245e00-fc0f-11ea-8c52-1af19e6afed2.png)
> 补充一些运行环境：
> `MiraiOK 20200915.071520 windows-386`
> `Backend: version 1.0-M4, built on 2020-09-13 02:19:35`
> `Frontend Pure: version 1.0-M4`


尝试用管理员权限启动

**Comment by PeratX** [comment]
日志请给全,不要给一部分,建议复制完整

**Comment by AdorableParker** [comment]
日志我是截图完整了的，上下文是无关的聊天消息记录，网络图片确实是权限问题，已经解决
但本地图片的问题尚未解决，什么原因呢。
`2020-09-21 14:19:21 D/MiraiNative: [Ikaros CQCode] [CQ:image,file=D:\Program Files (x86)\MiraiOk-M4\data\MiraiNative\data\com.adorableparker.github.ikaros_golang\time_txt\seto\Safe\00B76D44EBDC37A6DF0E33523A34AC82(1300×1300).jpg]

2020-09-21 14:19:21 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.sendMessage(GroupImpl.kt:293)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:155)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

**Comment by AdorableParker** [comment]
我又试过了用相对路径，图片存放在`.\data\image`下使用`[CQ:image,file=2.jpg]`这类是可以发送的，但是绝对路径就提示message is empty，是否是因为其他issue中提到的路径问题呢

**Comment by AdorableParker** [comment]
问题已解决，非bug，是我图片路径获取时发生的错误

**Comment by PeratX** [comment]
解决就好
